-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

DROP TABLE IF EXISTS public."Tickets";

CREATE TABLE IF NOT EXISTS public."Tickets"
(
    "ticketID" integer,
    vio_code integer NOT NULL,
    address character varying(255) NOT NULL,
	"makeID" integer NOT NULL,
    time_of_day character varying(255) NOT NULL,
    tick_date date NOT NULL,
    tick_time time without time zone NOT NULL,
	car_plate_exp character varying(25),
    remarks character varying(255)
);

DROP TABLE IF EXISTS public."Locations";

CREATE TABLE IF NOT EXISTS public."Locations"
(
    address character varying(255) NOT NULL,
    street character varying(255) NOT NULL,
    "lot/garage" character varying(25)
);

DROP TABLE IF EXISTS public."Vehicle";

CREATE TABLE IF NOT EXISTS public."Vehicle"
(
    "makeID" integer,
    car_make character varying(25),
    car_type character varying(25),
    car_color character varying(25)
);

DROP TABLE IF EXISTS public."Violations";

CREATE TABLE IF NOT EXISTS public."Violations"
(
    vio_code integer,
    vio_description character varying(255) NOT NULL,
    vio_type character varying(255) NOT NULL
);

INSERT INTO "Tickets" ("ticketID", vio_code, address, "makeID", time_of_day, tick_date, tick_time, car_plate_exp, remarks)
Select "ticketID",
vio_code,
address, 
"makeID",
time_of_day, 
tick_date, 
tick_time,
car_plate_exp,
remarks
FROM "DOTclean";

INSERT INTO "Locations" (address, street, "lot/garage")
Select address,
TRIM(max(street)) as street,
max("lot/garage") as "lot/garage"
from "DOTclean"
group by address;

INSERT INTO "Vehicle" ("makeID", car_make, car_type, car_color)
Select DISTINCT "makeID",
car_make,
car_type,
car_color
From "DOTclean";

INSERT INTO "Violations" (vio_code, vio_description, vio_type)
SELECT DISTINCT vio_code,
vio_description,
vio_type
FROM "DOTclean";

ALTER TABLE IF EXISTS public."Tickets"
	ADD PRIMARY KEY ("ticketID");

ALTER TABLE IF EXISTS public."Locations"
	ADD PRIMARY KEY (address);
	
ALTER TABLE IF EXISTS public."Vehicle"
	ADD PRIMARY KEY ("makeID");

ALTER TABLE IF EXISTS public."Violations"
	ADD PRIMARY KEY (vio_code);

ALTER TABLE IF EXISTS public."Tickets"
    ADD CONSTRAINT FK_address FOREIGN KEY (address)
    REFERENCES public."Locations" (address) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Tickets"
    ADD CONSTRAINT FK_violation FOREIGN KEY (vio_code)
    REFERENCES public."Violations" (vio_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
	
ALTER TABLE IF EXISTS public."Tickets"
    ADD CONSTRAINT FK_make FOREIGN KEY ("makeID")
    REFERENCES public."Vehicle" ("makeID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
	
END;
